# Generated by Django 5.0.3 on 2024-04-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_firstname_myuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='firstname',
        ),
    ]
