# Generated by Django 5.0.3 on 2024-04-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_myuser_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='firstname',
            new_name='name',
        ),
    ]
